/* location_geocode.c generated by valac 0.56.18, the Vala compiler
 * generated from location_geocode.vala, do not modify */

/*
 * Simple Nominatim-based ZIP -> city resolver.
 * Uses OpenStreetMap Nominatim public endpoint. This is intended for
 * low-volume lookups (please respect Nominatim usage policy). No API
 * key is required. Results are delivered asynchronously via the
 * provided callback on the main thread.
 */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <libsoup/soup.h>
#include <json-glib/json-glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef void (*GeoLookupResult) (const gchar* city, const gchar* _error_, gpointer user_data);

#define TYPE_LOCATION_GEOCODE (location_geocode_get_type ())
#define LOCATION_GEOCODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LOCATION_GEOCODE, LocationGeocode))
#define LOCATION_GEOCODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LOCATION_GEOCODE, LocationGeocodeClass))
#define IS_LOCATION_GEOCODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LOCATION_GEOCODE))
#define IS_LOCATION_GEOCODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LOCATION_GEOCODE))
#define LOCATION_GEOCODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LOCATION_GEOCODE, LocationGeocodeClass))

typedef struct _LocationGeocode LocationGeocode;
typedef struct _LocationGeocodeClass LocationGeocodeClass;
typedef struct _LocationGeocodePrivate LocationGeocodePrivate;
enum  {
	LOCATION_GEOCODE_0_PROPERTY,
	LOCATION_GEOCODE_NUM_PROPERTIES
};
static GParamSpec* location_geocode_properties[LOCATION_GEOCODE_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;
typedef struct _Block2Data Block2Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_SoupBuffer_free0(var) ((var == NULL) ? NULL : (var = (_vala_SoupBuffer_free (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
typedef struct _Block3Data Block3Data;
typedef struct _Block4Data Block4Data;
typedef struct _Block5Data Block5Data;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_thread_unref0(var) ((var == NULL) ? NULL : (var = (g_thread_unref (var), NULL)))

struct _LocationGeocode {
	GObject parent_instance;
	LocationGeocodePrivate * priv;
};

struct _LocationGeocodeClass {
	GObjectClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	gchar* zip;
	GeoLookupResult cb;
	gpointer cb_target;
};

struct _Block2Data {
	int _ref_count_;
	Block1Data * _data1_;
	SoupMessage* msg;
};

struct _Block3Data {
	int _ref_count_;
	Block2Data * _data2_;
	gchar* captured_city;
	gchar* captured_err;
};

struct _Block4Data {
	int _ref_count_;
	Block2Data * _data2_;
	gchar* captured_state;
	gchar* captured_err2;
};

struct _Block5Data {
	int _ref_count_;
	Block1Data * _data1_;
	GError* e;
};

static gpointer location_geocode_parent_class = NULL;

VALA_EXTERN GType location_geocode_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (LocationGeocode, g_object_unref)
VALA_EXTERN void location_geocode_lookup_zip_async (const gchar* zip,
                                        GeoLookupResult cb,
                                        gpointer cb_target);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void* __lambda4_ (Block1Data* _data1_);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static gboolean ____lambda5_ (Block2Data* _data2_);
static gboolean _____lambda5__gsource_func (gpointer self);
static void _vala_SoupBuffer_free (SoupBuffer* self);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static gboolean ____lambda6_ (Block2Data* _data2_);
static gboolean _____lambda6__gsource_func (gpointer self);
static void _vala_JsonNode_free (JsonNode* self);
static gboolean ____lambda7_ (Block2Data* _data2_);
static gboolean _____lambda7__gsource_func (gpointer self);
static gboolean ____lambda8_ (Block2Data* _data2_);
static gboolean _____lambda8__gsource_func (gpointer self);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static gboolean ____lambda9_ (Block3Data* _data3_);
static gboolean _____lambda9__gsource_func (gpointer self);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static gboolean _____lambda10_ (Block4Data* _data4_);
static gboolean ______lambda10__gsource_func (gpointer self);
static gboolean _____lambda11_ (Block2Data* _data2_);
static gboolean ______lambda11__gsource_func (gpointer self);
static Block5Data* block5_data_ref (Block5Data* _data5_);
static void block5_data_unref (void * _userdata_);
static gboolean ___lambda12_ (Block5Data* _data5_);
static gboolean ____lambda12__gsource_func (gpointer self);
static gpointer ___lambda4__gthread_func (gpointer self);
VALA_EXTERN LocationGeocode* location_geocode_new (void);
VALA_EXTERN LocationGeocode* location_geocode_construct (GType object_type);
static GType location_geocode_get_type_once (void);

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_free0 (_data1_->zip);
		g_slice_free (Block1Data, _data1_);
	}
}

static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}

static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		_g_object_unref0 (_data2_->msg);
		block1_data_unref (_data2_->_data1_);
		_data2_->_data1_ = NULL;
		g_slice_free (Block2Data, _data2_);
	}
}

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	g_strstrip (_result_);
	result = _result_;
	return result;
}

static gboolean
____lambda5_ (Block2Data* _data2_)
{
	Block1Data* _data1_;
	SoupMessage* _tmp0_;
	guint _tmp1_;
	guint _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gboolean result;
	_data1_ = _data2_->_data1_;
	_tmp0_ = _data2_->msg;
	g_object_get (_tmp0_, "status-code", &_tmp1_, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup_printf ("%u", _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat ("HTTP error ", _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	_data1_->cb (NULL, _tmp6_, _data1_->cb_target);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	result = FALSE;
	return result;
}

static gboolean
_____lambda5__gsource_func (gpointer self)
{
	gboolean result;
	result = ____lambda5_ (self);
	return result;
}

static void
_vala_SoupBuffer_free (SoupBuffer* self)
{
	g_boxed_free (soup_buffer_get_type (), self);
}

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
	return g_boxed_copy (json_node_get_type (), self);
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
	return self ? _vala_JsonNode_copy (self) : NULL;
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static gboolean
____lambda6_ (Block2Data* _data2_)
{
	Block1Data* _data1_;
	gboolean result;
	_data1_ = _data2_->_data1_;
	_data1_->cb (NULL, "Unexpected response format", _data1_->cb_target);
	result = FALSE;
	return result;
}

static gboolean
_____lambda6__gsource_func (gpointer self)
{
	gboolean result;
	result = ____lambda6_ (self);
	return result;
}

static void
_vala_JsonNode_free (JsonNode* self)
{
	g_boxed_free (json_node_get_type (), self);
}

static gboolean
____lambda7_ (Block2Data* _data2_)
{
	Block1Data* _data1_;
	gboolean result;
	_data1_ = _data2_->_data1_;
	_data1_->cb (NULL, "No results for ZIP", _data1_->cb_target);
	result = FALSE;
	return result;
}

static gboolean
_____lambda7__gsource_func (gpointer self)
{
	gboolean result;
	result = ____lambda7_ (self);
	return result;
}

static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

static gboolean
____lambda8_ (Block2Data* _data2_)
{
	Block1Data* _data1_;
	gboolean result;
	_data1_ = _data2_->_data1_;
	_data1_->cb (NULL, "No address in result", _data1_->cb_target);
	result = FALSE;
	return result;
}

static gboolean
_____lambda8__gsource_func (gpointer self)
{
	gboolean result;
	result = ____lambda8_ (self);
	return result;
}

static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		_g_free0 (_data3_->captured_err);
		_g_free0 (_data3_->captured_city);
		block2_data_unref (_data3_->_data2_);
		_data3_->_data2_ = NULL;
		g_slice_free (Block3Data, _data3_);
	}
}

static gboolean
____lambda9_ (Block3Data* _data3_)
{
	Block2Data* _data2_;
	Block1Data* _data1_;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gboolean result;
	_data2_ = _data3_->_data2_;
	_data1_ = _data2_->_data1_;
	_tmp0_ = _data3_->captured_city;
	_tmp1_ = _data3_->captured_err;
	_data1_->cb (_tmp0_, _tmp1_, _data1_->cb_target);
	result = FALSE;
	return result;
}

static gboolean
_____lambda9__gsource_func (gpointer self)
{
	gboolean result;
	result = ____lambda9_ (self);
	return result;
}

static Block4Data*
block4_data_ref (Block4Data* _data4_)
{
	g_atomic_int_inc (&_data4_->_ref_count_);
	return _data4_;
}

static void
block4_data_unref (void * _userdata_)
{
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
		_g_free0 (_data4_->captured_err2);
		_g_free0 (_data4_->captured_state);
		block2_data_unref (_data4_->_data2_);
		_data4_->_data2_ = NULL;
		g_slice_free (Block4Data, _data4_);
	}
}

static gboolean
_____lambda10_ (Block4Data* _data4_)
{
	Block2Data* _data2_;
	Block1Data* _data1_;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gboolean result;
	_data2_ = _data4_->_data2_;
	_data1_ = _data2_->_data1_;
	_tmp0_ = _data4_->captured_state;
	_tmp1_ = _data4_->captured_err2;
	_data1_->cb (_tmp0_, _tmp1_, _data1_->cb_target);
	result = FALSE;
	return result;
}

static gboolean
______lambda10__gsource_func (gpointer self)
{
	gboolean result;
	result = _____lambda10_ (self);
	return result;
}

static gboolean
_____lambda11_ (Block2Data* _data2_)
{
	Block1Data* _data1_;
	gboolean result;
	_data1_ = _data2_->_data1_;
	_data1_->cb (NULL, "Unable to determine city/state", _data1_->cb_target);
	result = FALSE;
	return result;
}

static gboolean
______lambda11__gsource_func (gpointer self)
{
	gboolean result;
	result = _____lambda11_ (self);
	return result;
}

static Block5Data*
block5_data_ref (Block5Data* _data5_)
{
	g_atomic_int_inc (&_data5_->_ref_count_);
	return _data5_;
}

static void
block5_data_unref (void * _userdata_)
{
	Block5Data* _data5_;
	_data5_ = (Block5Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data5_->_ref_count_)) {
		_g_error_free0 (_data5_->e);
		block1_data_unref (_data5_->_data1_);
		_data5_->_data1_ = NULL;
		g_slice_free (Block5Data, _data5_);
	}
}

static gboolean
___lambda12_ (Block5Data* _data5_)
{
	Block1Data* _data1_;
	GError* _tmp0_;
	const gchar* _tmp1_;
	gboolean result;
	_data1_ = _data5_->_data1_;
	_tmp0_ = _data5_->e;
	_tmp1_ = _tmp0_->message;
	_data1_->cb (NULL, _tmp1_, _data1_->cb_target);
	result = FALSE;
	return result;
}

static gboolean
____lambda12__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda12_ (self);
	return result;
}

static void*
__lambda4_ (Block1Data* _data1_)
{
	GError* _inner_error0_ = NULL;
	void* result;
	{
		Block2Data* _data2_;
		SoupSession* session = NULL;
		SoupSession* _tmp0_;
		gchar* q = NULL;
		gchar* _tmp1_;
		gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* url = NULL;
		const gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		const gchar* _tmp10_;
		SoupMessage* _tmp11_;
		SoupMessage* _tmp12_;
		SoupMessageHeaders* _tmp13_;
		SoupSession* _tmp14_;
		SoupMessage* _tmp15_;
		SoupMessage* _tmp16_;
		guint _tmp17_;
		guint _tmp18_;
		gchar* body = NULL;
		SoupMessage* _tmp19_;
		SoupMessageBody* _tmp20_;
		SoupBuffer* _tmp21_;
		SoupBuffer* _tmp22_;
		guint8* _tmp23_;
		gint _tmp23__length1;
		gchar* _tmp24_;
		gchar* _tmp25_;
		JsonParser* parser = NULL;
		JsonParser* _tmp26_;
		JsonParser* _tmp27_;
		const gchar* _tmp28_;
		JsonNode* root = NULL;
		JsonParser* _tmp29_;
		JsonNode* _tmp30_;
		JsonNode* _tmp31_;
		JsonArray* arr = NULL;
		JsonArray* _tmp35_;
		JsonObject* first = NULL;
		JsonArray* _tmp36_;
		JsonNode* _tmp37_;
		JsonObject* _tmp38_;
		JsonObject* _tmp39_;
		JsonObject* _tmp40_;
		JsonObject* addr = NULL;
		JsonObject* _tmp41_;
		JsonObject* _tmp42_;
		JsonObject* _tmp43_;
		gchar* city = NULL;
		gchar* _tmp44_;
		JsonObject* _tmp45_;
		gchar* state = NULL;
		gchar* _tmp61_;
		JsonObject* _tmp62_;
		gboolean _tmp66_ = FALSE;
		const gchar* _tmp67_;
		gint _tmp68_;
		gint _tmp69_;
		_data2_ = g_slice_new0 (Block2Data);
		_data2_->_ref_count_ = 1;
		_data2_->_data1_ = block1_data_ref (_data1_);
		_tmp0_ = soup_session_new ();
		session = _tmp0_;
		_tmp1_ = string_strip (_data1_->zip);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_strconcat (_tmp2_, " USA", NULL);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		q = _tmp4_;
		_tmp5_ = q;
		_tmp6_ = g_uri_escape_string (_tmp5_, NULL, TRUE);
		_tmp7_ = _tmp6_;
		_tmp8_ = g_strconcat ("https://nominatim.openstreetmap.org/search?format=json&addressdetails=" \
"1&countrycodes=us&limit=3&q=", _tmp7_, NULL);
		_tmp9_ = _tmp8_;
		_g_free0 (_tmp7_);
		url = _tmp9_;
		_tmp10_ = url;
		_tmp11_ = soup_message_new ("GET", _tmp10_);
		_data2_->msg = _tmp11_;
		_tmp12_ = _data2_->msg;
		_tmp13_ = _tmp12_->request_headers;
		soup_message_headers_append (_tmp13_, "User-Agent", "paperboy/0.1 (contact@paperboy.example)");
		_tmp14_ = session;
		_tmp15_ = _data2_->msg;
		soup_session_send_message (_tmp14_, _tmp15_);
		_tmp16_ = _data2_->msg;
		g_object_get (_tmp16_, "status-code", &_tmp17_, NULL);
		_tmp18_ = _tmp17_;
		if (_tmp18_ != ((guint) 200)) {
			g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _____lambda5__gsource_func, block2_data_ref (_data2_), block2_data_unref);
			result = NULL;
			_g_free0 (url);
			_g_free0 (q);
			_g_object_unref0 (session);
			block2_data_unref (_data2_);
			_data2_ = NULL;
			return result;
		}
		_tmp19_ = _data2_->msg;
		_tmp20_ = _tmp19_->response_body;
		_tmp21_ = soup_message_body_flatten (_tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = _tmp22_->data;
		_tmp23__length1 = _tmp22_->length;
		_tmp24_ = g_strdup ((const gchar*) _tmp23_);
		_tmp25_ = _tmp24_;
		__vala_SoupBuffer_free0 (_tmp22_);
		body = _tmp25_;
		_tmp26_ = json_parser_new ();
		parser = _tmp26_;
		_tmp27_ = parser;
		_tmp28_ = body;
		json_parser_load_from_data (_tmp27_, _tmp28_, (gssize) -1, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (parser);
			_g_free0 (body);
			_g_free0 (url);
			_g_free0 (q);
			_g_object_unref0 (session);
			block2_data_unref (_data2_);
			_data2_ = NULL;
			goto __catch0_g_error;
		}
		_tmp29_ = parser;
		_tmp30_ = json_parser_get_root (_tmp29_);
		_tmp31_ = __vala_JsonNode_copy0 (_tmp30_);
		root = _tmp31_;
		arr = NULL;
		{
			JsonNode* _tmp32_;
			JsonArray* _tmp33_;
			JsonArray* _tmp34_;
			_tmp32_ = root;
			_tmp33_ = json_node_get_array (_tmp32_);
			_tmp34_ = _json_array_ref0 (_tmp33_);
			_json_array_unref0 (arr);
			arr = _tmp34_;
		}
		goto __finally1;
		__catch1_g_error:
		{
			g_clear_error (&_inner_error0_);
			g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _____lambda6__gsource_func, block2_data_ref (_data2_), block2_data_unref);
			result = NULL;
			_json_array_unref0 (arr);
			__vala_JsonNode_free0 (root);
			_g_object_unref0 (parser);
			_g_free0 (body);
			_g_free0 (url);
			_g_free0 (q);
			_g_object_unref0 (session);
			block2_data_unref (_data2_);
			_data2_ = NULL;
			return result;
		}
		__finally1:
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_json_array_unref0 (arr);
			__vala_JsonNode_free0 (root);
			_g_object_unref0 (parser);
			_g_free0 (body);
			_g_free0 (url);
			_g_free0 (q);
			_g_object_unref0 (session);
			block2_data_unref (_data2_);
			_data2_ = NULL;
			goto __catch0_g_error;
		}
		_tmp35_ = arr;
		if (json_array_get_length (_tmp35_) == ((guint) 0)) {
			g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _____lambda7__gsource_func, block2_data_ref (_data2_), block2_data_unref);
			result = NULL;
			_json_array_unref0 (arr);
			__vala_JsonNode_free0 (root);
			_g_object_unref0 (parser);
			_g_free0 (body);
			_g_free0 (url);
			_g_free0 (q);
			_g_object_unref0 (session);
			block2_data_unref (_data2_);
			_data2_ = NULL;
			return result;
		}
		_tmp36_ = arr;
		_tmp37_ = json_array_get_element (_tmp36_, (guint) 0);
		_tmp38_ = json_node_get_object (_tmp37_);
		_tmp39_ = _json_object_ref0 (_tmp38_);
		first = _tmp39_;
		_tmp40_ = first;
		if (!json_object_has_member (_tmp40_, "address")) {
			g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _____lambda8__gsource_func, block2_data_ref (_data2_), block2_data_unref);
			result = NULL;
			_json_object_unref0 (first);
			_json_array_unref0 (arr);
			__vala_JsonNode_free0 (root);
			_g_object_unref0 (parser);
			_g_free0 (body);
			_g_free0 (url);
			_g_free0 (q);
			_g_object_unref0 (session);
			block2_data_unref (_data2_);
			_data2_ = NULL;
			return result;
		}
		_tmp41_ = first;
		_tmp42_ = json_object_get_object_member (_tmp41_, "address");
		_tmp43_ = _json_object_ref0 (_tmp42_);
		addr = _tmp43_;
		_tmp44_ = g_strdup ("");
		city = _tmp44_;
		_tmp45_ = addr;
		if (json_object_has_member (_tmp45_, "city")) {
			JsonObject* _tmp46_;
			const gchar* _tmp47_;
			gchar* _tmp48_;
			_tmp46_ = addr;
			_tmp47_ = json_object_get_string_member (_tmp46_, "city");
			_tmp48_ = g_strdup (_tmp47_);
			_g_free0 (city);
			city = _tmp48_;
		} else {
			JsonObject* _tmp49_;
			_tmp49_ = addr;
			if (json_object_has_member (_tmp49_, "town")) {
				JsonObject* _tmp50_;
				const gchar* _tmp51_;
				gchar* _tmp52_;
				_tmp50_ = addr;
				_tmp51_ = json_object_get_string_member (_tmp50_, "town");
				_tmp52_ = g_strdup (_tmp51_);
				_g_free0 (city);
				city = _tmp52_;
			} else {
				JsonObject* _tmp53_;
				_tmp53_ = addr;
				if (json_object_has_member (_tmp53_, "village")) {
					JsonObject* _tmp54_;
					const gchar* _tmp55_;
					gchar* _tmp56_;
					_tmp54_ = addr;
					_tmp55_ = json_object_get_string_member (_tmp54_, "village");
					_tmp56_ = g_strdup (_tmp55_);
					_g_free0 (city);
					city = _tmp56_;
				} else {
					JsonObject* _tmp57_;
					_tmp57_ = addr;
					if (json_object_has_member (_tmp57_, "county")) {
						JsonObject* _tmp58_;
						const gchar* _tmp59_;
						gchar* _tmp60_;
						_tmp58_ = addr;
						_tmp59_ = json_object_get_string_member (_tmp58_, "county");
						_tmp60_ = g_strdup (_tmp59_);
						_g_free0 (city);
						city = _tmp60_;
					}
				}
			}
		}
		_tmp61_ = g_strdup ("");
		state = _tmp61_;
		_tmp62_ = addr;
		if (json_object_has_member (_tmp62_, "state")) {
			JsonObject* _tmp63_;
			const gchar* _tmp64_;
			gchar* _tmp65_;
			_tmp63_ = addr;
			_tmp64_ = json_object_get_string_member (_tmp63_, "state");
			_tmp65_ = g_strdup (_tmp64_);
			_g_free0 (state);
			state = _tmp65_;
		}
		_tmp67_ = city;
		_tmp68_ = strlen (_tmp67_);
		_tmp69_ = _tmp68_;
		if (_tmp69_ > 0) {
			const gchar* _tmp70_;
			gint _tmp71_;
			gint _tmp72_;
			_tmp70_ = state;
			_tmp71_ = strlen (_tmp70_);
			_tmp72_ = _tmp71_;
			_tmp66_ = _tmp72_ > 0;
		} else {
			_tmp66_ = FALSE;
		}
		if (_tmp66_) {
			Block3Data* _data3_;
			gchar* out = NULL;
			const gchar* _tmp73_;
			gchar* _tmp74_;
			gchar* _tmp75_;
			const gchar* _tmp76_;
			gchar* _tmp77_;
			gchar* _tmp78_;
			const gchar* _tmp79_;
			gchar* _tmp80_;
			_data3_ = g_slice_new0 (Block3Data);
			_data3_->_ref_count_ = 1;
			_data3_->_data2_ = block2_data_ref (_data2_);
			_tmp73_ = city;
			_tmp74_ = g_strconcat (_tmp73_, ", ", NULL);
			_tmp75_ = _tmp74_;
			_tmp76_ = state;
			_tmp77_ = g_strconcat (_tmp75_, _tmp76_, NULL);
			_tmp78_ = _tmp77_;
			_g_free0 (_tmp75_);
			out = _tmp78_;
			_tmp79_ = out;
			_tmp80_ = g_strdup (_tmp79_);
			_data3_->captured_city = _tmp80_;
			_data3_->captured_err = NULL;
			g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _____lambda9__gsource_func, block3_data_ref (_data3_), block3_data_unref);
			result = NULL;
			_g_free0 (out);
			block3_data_unref (_data3_);
			_data3_ = NULL;
			_g_free0 (state);
			_g_free0 (city);
			_json_object_unref0 (addr);
			_json_object_unref0 (first);
			_json_array_unref0 (arr);
			__vala_JsonNode_free0 (root);
			_g_object_unref0 (parser);
			_g_free0 (body);
			_g_free0 (url);
			_g_free0 (q);
			_g_object_unref0 (session);
			block2_data_unref (_data2_);
			_data2_ = NULL;
			return result;
		} else {
			const gchar* _tmp81_;
			gint _tmp82_;
			gint _tmp83_;
			_tmp81_ = state;
			_tmp82_ = strlen (_tmp81_);
			_tmp83_ = _tmp82_;
			if (_tmp83_ > 0) {
				Block4Data* _data4_;
				const gchar* _tmp84_;
				gchar* _tmp85_;
				_data4_ = g_slice_new0 (Block4Data);
				_data4_->_ref_count_ = 1;
				_data4_->_data2_ = block2_data_ref (_data2_);
				_tmp84_ = state;
				_tmp85_ = g_strdup (_tmp84_);
				_data4_->captured_state = _tmp85_;
				_data4_->captured_err2 = NULL;
				g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ______lambda10__gsource_func, block4_data_ref (_data4_), block4_data_unref);
				result = NULL;
				block4_data_unref (_data4_);
				_data4_ = NULL;
				_g_free0 (state);
				_g_free0 (city);
				_json_object_unref0 (addr);
				_json_object_unref0 (first);
				_json_array_unref0 (arr);
				__vala_JsonNode_free0 (root);
				_g_object_unref0 (parser);
				_g_free0 (body);
				_g_free0 (url);
				_g_free0 (q);
				_g_object_unref0 (session);
				block2_data_unref (_data2_);
				_data2_ = NULL;
				return result;
			} else {
				g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ______lambda11__gsource_func, block2_data_ref (_data2_), block2_data_unref);
				result = NULL;
				_g_free0 (state);
				_g_free0 (city);
				_json_object_unref0 (addr);
				_json_object_unref0 (first);
				_json_array_unref0 (arr);
				__vala_JsonNode_free0 (root);
				_g_object_unref0 (parser);
				_g_free0 (body);
				_g_free0 (url);
				_g_free0 (q);
				_g_object_unref0 (session);
				block2_data_unref (_data2_);
				_data2_ = NULL;
				return result;
			}
		}
		_g_free0 (state);
		_g_free0 (city);
		_json_object_unref0 (addr);
		_json_object_unref0 (first);
		_json_array_unref0 (arr);
		__vala_JsonNode_free0 (root);
		_g_object_unref0 (parser);
		_g_free0 (body);
		_g_free0 (url);
		_g_free0 (q);
		_g_object_unref0 (session);
		block2_data_unref (_data2_);
		_data2_ = NULL;
	}
	goto __finally0;
	__catch0_g_error:
	{
		Block5Data* _data5_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_data5_ = g_slice_new0 (Block5Data);
		_data5_->_ref_count_ = 1;
		_data5_->_data1_ = block1_data_ref (_data1_);
		g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ____lambda12__gsource_func, block5_data_ref (_data5_), block5_data_unref);
		block5_data_unref (_data5_);
		_data5_ = NULL;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	result = NULL;
	return result;
}

static gpointer
___lambda4__gthread_func (gpointer self)
{
	gpointer result;
	result = __lambda4_ (self);
	block1_data_unref (self);
	return result;
}

void
location_geocode_lookup_zip_async (const gchar* zip,
                                   GeoLookupResult cb,
                                   gpointer cb_target)
{
	Block1Data* _data1_;
	gchar* _tmp0_;
	GThread* _tmp1_;
	GThread* _tmp2_;
	g_return_if_fail (zip != NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_tmp0_ = g_strdup (zip);
	_g_free0 (_data1_->zip);
	_data1_->zip = _tmp0_;
	_data1_->cb = cb;
	_data1_->cb_target = cb_target;
	_tmp1_ = g_thread_new ("geo-lookup", ___lambda4__gthread_func, block1_data_ref (_data1_));
	_tmp2_ = _tmp1_;
	_g_thread_unref0 (_tmp2_);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}

LocationGeocode*
location_geocode_construct (GType object_type)
{
	LocationGeocode * self = NULL;
	self = (LocationGeocode*) g_object_new (object_type, NULL);
	return self;
}

LocationGeocode*
location_geocode_new (void)
{
	return location_geocode_construct (TYPE_LOCATION_GEOCODE);
}

static void
location_geocode_class_init (LocationGeocodeClass * klass,
                             gpointer klass_data)
{
	location_geocode_parent_class = g_type_class_peek_parent (klass);
}

static void
location_geocode_instance_init (LocationGeocode * self,
                                gpointer klass)
{
}

static GType
location_geocode_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (LocationGeocodeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) location_geocode_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LocationGeocode), 0, (GInstanceInitFunc) location_geocode_instance_init, NULL };
	GType location_geocode_type_id;
	location_geocode_type_id = g_type_register_static (G_TYPE_OBJECT, "LocationGeocode", &g_define_type_info, 0);
	return location_geocode_type_id;
}

GType
location_geocode_get_type (void)
{
	static volatile gsize location_geocode_type_id__once = 0;
	if (g_once_init_enter (&location_geocode_type_id__once)) {
		GType location_geocode_type_id;
		location_geocode_type_id = location_geocode_get_type_once ();
		g_once_init_leave (&location_geocode_type_id__once, location_geocode_type_id);
	}
	return location_geocode_type_id__once;
}

